In [1]:
import numpy as np

**Задание 1**
Создайте numpyarray с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [2]:
n = 10
np.arange(n - 1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = 10
import random

In [5]:
z = np.diag(np.arange(n, 0, -1), k = 0)
print(z)

[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]


In [6]:
sum_diag = 0
for i in range(n):
    sum_diag += z[i][i]
print(sum_diag)

55


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [7]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
import pandas as pd

**Задание 4**
Для датафреймаlog из материалов занятия создайте столбец source_type по следующим правилам:
- если источник traffic_source равен yandex или google, то в source_type ставится organic
- для источников paid и email из России - ставим ad
- для источников paid и email не из России - ставим other
- все остальные варианты берем из traffic_source без изменений

In [9]:
log = pd.read_csv('visit_log.csv', sep=';')
log.head()

timestamp    visit_id                                 url  region  \
0  1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3  Russia   
1  1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a  Russia   
2  1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15  Russia   
3  1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15  Russia   
4  1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15  Russia   

      user_id traffic_source  
0  b1613cc09f         yandex  
1  4c3ec14bee         direct  
2  a8c40697fb         yandex  
3  521ac1d6a0         yandex  
4  d7323c571c         yandex

In [10]:
log.loc[log.traffic_source.isin(['yandex','google']), 'source_type'] = 'organic'
log.loc[((log.traffic_source.isin(['paid','email'])) & (log.region == 'Russia')), 'source_type'] = 'ad'
log.loc[((log.traffic_source.isin(['paid','email'])) & ~(log.region == 'Russia')), 'source_type'] = 'other'
log.head(10)

timestamp    visit_id                                 url  region  \
0  1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3  Russia   
1  1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a  Russia   
2  1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15  Russia   
3  1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15  Russia   
4  1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15  Russia   
5  1549980742  8855508aad  https://host.ru/df646c3676cc259fa0  Russia   
6  1549980742  b0f66adc83  https://host.ru/b8b58337d272ee7b15  Russia   
7  1549980754  837885c8f8  https://host.ru/108ce4b365afb7b88e  Russia   
8  1549980760  af5570f5a1  https://host.ru/3004a8273caeef2867   China   
9  1549980765  3e7077fd2f  https://host.ru/df646c3676cc259fa0  Russia   

      user_id traffic_source source_type  
0  b1613cc09f         yandex     organic  
1  4c3ec14bee         direct         NaN  
2  a8c40697fb         yandex     organic  
3  521ac1d6a0         yandex     organic  
4  d7323c571c         yandex     organic  
5  fc43898e47         yandex     organic  
6  13fc55e781           paid          ad  
7  cb5082b6f6         direct         NaN  
8  45664f7af2         direct         NaN  
9  6f9de8c8b6          email          ad

In [11]:
log[log.source_type == 'other'].head()

timestamp    visit_id                                 url   region  \
15  1549980797  5322fecfc9  https://host.ru/4adc8a29b212051b04  Belarus   
17  1549980807  0a88111852  https://host.ru/2fcb223266880ccf57  Ukraine   
20  1549980816  de47c9b27e  https://host.ru/8fe7c39e5c598bbc54  Ukraine   
33  1549980897  7f9c9e31ac  https://host.ru/ac2d98a5a63e7c6e28  Belarus   
43  1549980949  859732b973  https://host.ru/4adc8a29b212051b04  Ukraine   

       user_id traffic_source source_type  
15  9a45d98867           paid       other  
17  a2ba8fa3db           paid       other  
20  2f25b6e26a          email       other  
33  38f45e7f9b          email       other  
43  80f2fd30f8          email       other

**Задание 5**
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:
1. Прочитайте содержимое файла с датафрейм
2. Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [12]:
urls = pd.read_table('URLs.txt', header=0)
urls.head()

url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [13]:
print(urls.loc[3])

url    /politics/36188461-s-marta-zhizn-rossiyan-susc...
Name: 3, dtype: object


In [14]:
import re
regex_url = r'/\d{8}-'
urls[urls.url.str.contains(regex_url, regex = True)].head()

url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...